# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Elevator\Infrastructure\EventStoreUsingDbal:
        class: Elevator\Infrastructure\EventStoreUsingDbal

    Elevator\Domain\BuildingRepository:
        class: Elevator\Domain\BuildingRepository
        arguments:
            - '@Elevator\Infrastructure\EventStoreUsingDbal'
            - '@Psr\EventDispatcher\EventDispatcherInterface'

    Elevator\Domain\Handler\SequenceSimulator:
        class: Elevator\Domain\Handler\SequenceSimulator
        arguments:
            - '@Elevator\Domain\BuildingRepository'

    Projection:
        class: Elevator\Projection\ProjectSequencesToDbalReadModel
        tags:
            - { name: kernel.event_listener, event: 'domain.events' }

    Elevator\Application\SequenceFinder:
        class: Elevator\Infrastructure\SequenceFinderUsingDbal

    Elevator\Application\Cli\RunSequences:
        class: Elevator\Application\Cli\RunSequences
